services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 54340:5432
    environment:
      POSTGRES_USER: me
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: my_task_manager_db
    volumes:
      - ./db/data:/var/lib/postgresql/data