#? Users
GET http://localhost:3333/users

###
GET http://localhost:3333/users/1

###
GET http://localhost:3333/users/me

###
POST http://localhost:3333/auth/register
Content-Type: application/json

{
  "username":"test@testing.com",
  "password":"12345"
}

###
POST http://localhost:3333/auth/login
Content-Type: application/json

{
  "username":"test@testing.com",
  "password":"12345"
}

###
GET http://localhost:3333/users
Authorization: Bearer eyJhbGciOiJIUzIt1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiZWF0IjoxNzMwNzc1MjU3LCJpYXQiOjE3MzA3NzUxOTd9LCJzZXNzaW9uIjoiOThjODFiNTctNDEwMy01Y2RjLWE4NWEtYmI0YTU2YzBjZmNkIn0.JM4Pr0mjIkkktCIMGkuHKXAML7qQuviTh3KELfkju98

###
PUT http://localhost:3333/users/1
Content-Type: application/json

{
  "username":"user1@testing.com",
  "password":"12345Updated"
}

###
DELETE http://localhost:3333/users/1
Content-Type: application/json

#? Entries
###
GET http://localhost:3333/entries

###
GET http://localhost:3333/entries/1

###
POST http://localhost:3333/entries
Content-Type: application/json

{
  "title":"Test",
  "content":"Test Content"
}

###
PUT http://localhost:3333/entries/3
Content-Type: application/json

{
  "Title":"Test Updated",
  "Content":"Test Content Updated",
}

###
DELETE http://localhost:3333/entries/3
Content-Type: application/json

